

### Por defecto
GET {{APP_URL}} HTTP/1.1
Content-Type: application/json

### Nuevo
GET {{APP_URL}}/nuevo HTTP/1.1
Content-Type: application/json
Auth: 1234

### Ruta
GET {{APP_URL}}/ruta HTTP/1.1
Content-Type: application/json
Auth: 1234
