@APP_URL = {{$dotenv APP_URL}}
@contentType = application/json
@feature = brands

### getAll
GET {{APP_URL}}/{{feature}}?limit=5&offset=0 HTTP/1.1

### getOne
GET {{APP_URL}}/{{feature}}/1 HTTP/1.1

### Create
POST {{APP_URL}}/{{feature}} HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Brand 4",
    "image": "page.com"
}

### Update
PUT {{APP_URL}}/{{feature}}/2 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Brand 2"
}

### delete
DELETE {{APP_URL}}/{{feature}}/2 HTTP/1.1
