@APP_URL = {{$dotenv APP_URL}}
@contentType = application/json
@feature = products

### getAll
GET {{APP_URL}}/{{feature}}?limit=3&offset=0 HTTP/1.1

### getOne
GET {{APP_URL}}/{{feature}}/1 HTTP/1.1

### Create
POST {{APP_URL}}/{{feature}} HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Product 5",
    "description": "Description product 5",
    "price": 200,
    "image": "pagina.com",
    "stock": 2,
    "brandId": 1,
    "categoriesIds": [1]
}

### Update
PUT {{APP_URL}}/{{feature}}/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "brandId": 1,
    "categoriesIds": [1,2]
}

### Add category by Product
PUT {{APP_URL}}/{{feature}}/2/category/1 HTTP/1.1

### delete
DELETE {{APP_URL}}/{{feature}}/1 HTTP/1.1

### delete category by Product
DELETE {{APP_URL}}/{{feature}}/2/category/1 HTTP/1.1
