@APP_URL = {{$dotenv APP_URL}}
@contentType = application/json
@feature = tasks

### getAll
GET {{APP_URL}}/{{feature}} HTTP/1.1

### getOne
GET {{APP_URL}}/{{feature}}/1 HTTP/1.1

### Create
POST {{APP_URL}}/{{feature}} HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "mail2@mail.com",
    "password": "1212",
    "role": "admin"
}

### Update
PUT {{APP_URL}}/{{feature}}/2 HTTP/1.1
Content-Type: {{contentType}}

{
    "password": "12122"
}

### delete
DELETE {{APP_URL}}/{{feature}}/1 HTTP/1.1

### getOrders
GET {{APP_URL}}/{{feature}}/1/orders HTTP/1.1
