@APP_URL = {{$dotenv APP_URL}}
@contentType = application/json
@feature = users

### getAll
GET {{APP_URL}}/{{feature}} HTTP/1.1

### getOne
GET {{APP_URL}}/{{feature}}/1 HTTP/1.1

### Create
POST {{APP_URL}}/{{feature}} HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "customer@mail.com",
    "password": "121212",
    "role": "customer",
    "customerId": 1
}

### Update
PUT {{APP_URL}}/{{feature}}/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "password": "121222"
}

### delete
DELETE {{APP_URL}}/{{feature}}/2 HTTP/1.1

